### ISSUE TITLE
最新版本切换到GPT4会抛异常

### ISSUE THREAD

**Issue by a137235** [Kerwin1202/chatgpt-web#152]
当apiKey不支持GPT4，且切换到GPT4就会异常，而且切换回去也恢复不了

> Cannot read properties of null (reading 'toLowerCase')

**Comment by a137235** [comment]
而且普通用户有《用户管理》选项卡

**Comment by a137235** [comment]
`TypeError: Cannot read properties of null (reading 'toLowerCase')
 at initApi (/app/build/index.js:10056:15)
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at chatReplyProcess (/app/build/index.js:10098:17)
at <anonymous> (/app/build/index.js:10772:14)`

**Comment by ngloom** [comment]
切换模型后出错, 问题是切换回来依旧无法恢复正常...
TypeError: Cannot read properties of null (reading 'toLowerCase')
    at initApi (/app/build/index.js:10056:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at chatReplyProcess (/app/build/index.js:10098:17)
    at <anonymous> (/app/build/index.js:10772:14)

**Comment by Kerwin1202** [comment]
是最新版本吗，，不是的话是可能的

**Comment by ngloom** [comment]
@Kerwin1202  更新最新版本后解决, 感谢
