### ISSUE TITLE
docker部署启动过程中报错TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by karlcrane2015** [Kerwin1202/chatgpt-web#230]
以下为错误日志：
> chatgpt-web-service@1.0.0 prod /app
> esno ./build/index.js
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_URL]: Invalid URL
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at __defProp (/app/build/index.js:9685:17)
    at Object.<anonymous> (/app/build/index.js:11425:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.F (/app/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Kerwin1202** [comment]
这个看不出来是哪个的，如果是刚部署就报错，提供docker配置文件完整的 记得加 ``` 代码扩起来```

**Comment by jieny** [comment]
sudo docker run --name chatgpt-web -d -p 3002:3002 --env OPENAI_ACCESS_TOKEN=xxx --env API_REVERSE_PROXY=http://xxx/backend-api/conversation kerwin1202/chatgpt-web:latest

root@Linux62:~# sudo docker logs chatgpt-web2
node:internal/url:775
    this.#updateContext(bindingUrl.parse(input, base));
                                   ^

TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at file:///app/build/storage/mongo.js:9:19
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  code: 'ERR_INVALID_URL',
  input: 'undefined'
}

Node.js v20.10.0

**Comment by BobDu** [comment]
> TypeError: Invalid URL
> at new URL (node:internal/url:775:36)
> at file:///app/build/storage/mongo.js:9:19

很显然。环境变量没有提供 `MONGODB_URL`
