### ISSUE TITLE
服务端start报错，请问这个可能是什么原因？

### ISSUE THREAD

**Issue by Erimus-Koo** [Kerwin1202/chatgpt-web#289]
```
> chatgpt-web-service@1.0.0 start /Users/erimus/Downloads/chatgpt-web/service
> esno ./src/index.ts

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:743:13)
    at <anonymous> (/Users/erimus/Downloads/chatgpt-web/service/src/storage/mongo.ts:10:19)
    at Object.<anonymous> (/Users/erimus/Downloads/chatgpt-web/service/src/storage/mongo.ts:373:23)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Object.F (/Users/erimus/Downloads/chatgpt-web/service/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at <anonymous> (/Users/erimus/Downloads/chatgpt-web/service/src/storage/config.ts:6:47)
    at Object.<anonymous> (/Users/erimus/Downloads/chatgpt-web/service/src/storage/config.ts:141:23)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Object.F (/Users/erimus/Downloads/chatgpt-web/service/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at options (/Users/erimus/Downloads/chatgpt-web/service/src/chatgpt/index.ts:13:66)
    at Object.<anonymous> (/Users/erimus/Downloads/chatgpt-web/service/src/chatgpt/index.ts:398:10)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Object.F (/Users/erimus/Downloads/chatgpt-web/service/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at userId (/Users/erimus/Downloads/chatgpt-web/service/src/index.ts:7:106)
    at Object.<anonymous> (/Users/erimus/Downloads/chatgpt-web/service/src/index.ts:942:80)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Object.F (/Users/erimus/Downloads/chatgpt-web/service/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
```

本机本来就已经有mongo一直在跑，不知道有没有影响。

其他安装步骤都没问题，fork的源项目能跑通。

**Comment by Erimus-Koo** [comment]
发现是要设一个 `MONGODB_URL` 变量，readme沿用源项目的没有加，docker compose里加了，可以补一下文档。
