### ISSUE TITLE
v2.13.10 版本直接连接API收不到响应 

### ISSUE THREAD

**Issue by xiaoguaishou92** [Kerwin1202/chatgpt-web#407]
日志如下：
Server is running on port 3002
sendMessage (50 tokens) {
  max_tokens: 2048,
  model: 'gpt-4',
  temperature: undefined,
  top_p: undefined,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2024-01-11'
    },
    { role: 'user', content: '123', name: undefined }
  ],
  stream: true
}
TimeoutError: OpenAI timed out waiting for response
    at file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24
    at new Promise (<anonymous>)
    at pTimeout (file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
    at ChatGPTAPI.sendMessage (/app/node_modules/.pnpm/chatgpt@5.2.4/node_modules/chatgpt/src/chatgpt-api.ts:336:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatReplyProcess (file:///app/build/chatgpt/index.js:130:26)
    at async file:///app/build/index.js:335:18

第三方网站有扣费记录：
![image](https://github.com/Kerwin1202/chatgpt-web/assets/20310407/d180ba0e-d524-43e7-9a1c-18a48ee91a17)
本地对话页面是504
![image](https://github.com/Kerwin1202/chatgpt-web/assets/20310407/5fe61709-dcb9-4ce3-8e47-6532ad95e054)

**Comment by BobDu** [comment]
请求超时了。 大概率是你用的反代网站有问题。可以多试几下。
以防万一也可以再试一下 `2.13.8` 版本看看

**Comment by xiaoguaishou92** [comment]
> 请求超时了。 大概率是你用的反代网站有问题。可以多试几下。 以防万一也可以再试一下 `2.13.8` 版本看看

sendMessage (50 tokens) {
  max_tokens: 2048,
  model: 'gpt-4',
  temperature: undefined,
  top_p: undefined,
  presence_penalty: 1,
  messages: [
    {
      role: 'system',
      content: 'You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\n' +
        'Knowledge cutoff: 2021-09-01\n' +
        'Current date: 2024-01-11'
    },
    { role: 'user', content: '123', name: undefined }
  ],
  stream: true
}
TimeoutError: OpenAI timed out waiting for response
    at <anonymous> (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24)
    at new Promise (<anonymous>)
    at pTimeout (/app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
    at Object.sendMessage (/app/node_modules/.pnpm/chatgpt@5.2.4/node_modules/chatgpt/build/index.js:366:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at chatReplyProcess (/app/build/index.js:10771:22)
    at <anonymous> (/app/build/index.js:11377:14)

2.13.8  一样的报错。我在试试之前的版本

**Comment by xiaoguaishou92** [comment]
代理网站如下：https://api.megpt.me/
