### ISSUE TITLE
通过Access Token反向代理，回答字数过多会报错，无法显示完全

### ISSUE THREAD

**Issue by a137235** [Kerwin1202/chatgpt-web#52]
SyntaxError: Unexpected number in JSON at position 4
kerwin_chatgpt-app-1       |     at JSON.parse (<anonymous>)
kerwin_chatgpt-app-1       |     at onMessage (/app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:622:47)
kerwin_chatgpt-app-1       |     at <anonymous> (/app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:62:7)
kerwin_chatgpt-app-1       |     at parseEventStreamLine (/app/node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/src/parse.ts:125:17)

**Comment by TimeBye** [comment]
遇到同样的问题

**Comment by Kerwin1202** [comment]
现在有啥好用的社区反代吗，我之前试了都是超时，所以无法测试复现，得看看是不是上一层框架的问题

**Comment by TimeBye** [comment]
> 现在有啥好用的社区反代吗，我之前试了都是超时，所以无法测试复现，得看看是不是上一层框架的问题

https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy

大佬，社区的这个代理就可以 `https://ai.fakeopen.com/api/conversation`  @Kerwin1202

**Comment by Kerwin1202** [comment]
> > 现在有啥好用的社区反代吗，我之前试了都是超时，所以无法测试复现，得看看是不是上一层框架的问题
> 
> https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
> 
> 大佬，社区的这个代理就可以 `https://ai.fakeopen.com/api/conversation` @Kerwin1202

你正常吗，试了另一个也不行，我就没成功过accesstoken。。

<img width="506" alt="image" src="https://user-images.githubusercontent.com/16319833/233846819-96bb6d7a-2d09-4b5c-8ea6-50d1adf30056.png">
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/16319833/233846835-8608662c-a9eb-4d12-89bd-7baf7ce7dbc8.png">

**Comment by TimeBye** [comment]
<img width="1793" alt="image" src="https://user-images.githubusercontent.com/22651579/234244981-3b53dcbd-2a3a-45b7-8f36-8a7f37391a97.png">

我这里测试确实没有问题   代理可以用

**Comment by TimeBye** [comment]
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/22651579/234245849-e3379331-4cb4-4f54-bc92-20c5127e2209.png">
<img width="1806" alt="image" src="https://user-images.githubusercontent.com/22651579/234245984-55ed9d21-cdc9-4a46-8f9c-83bc2d7e98a3.png">

我搭建的这一个使用代理没有问题，可以给一下你的邮箱吗（临时邮箱也可）？我给你发我搭的这一个地址和用户名及密码

**Comment by Kerwin1202** [comment]
> <img alt="image" width="1788" src="https://user-images.githubusercontent.com/22651579/234245849-e3379331-4cb4-4f54-bc92-20c5127e2209.png">
> 
> <img alt="image" width="1806" src="https://user-images.githubusercontent.com/22651579/234245984-55ed9d21-cdc9-4a46-8f9c-83bc2d7e98a3.png">
> 
> 我搭建的这一个使用代理没有问题，可以给一下你的邮箱吗（临时邮箱也可）？我给你发我搭的这一个地址和用户名及密码

958686489@qq.com

**Comment by Kerwin1202** [comment]
倒不用了，刚才发现是我之前 token 找错了。 目前测试了下没啥问题。。不会报错。。。
