### ISSUE TITLE
邮件发送失败

### ISSUE THREAD

**Issue by jjustwin** [Kerwin1202/chatgpt-web#77]
以下是日志：
`Server is running on port 3002
/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:830
            return this._onError(new Error('Connection closed unexpectedly'), 'ECONNECTION', false, 'CONN');
                                 ^

Error: Connection closed unexpectedly
    at SMTPConnection._onClose (/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:830:34)
    at TLSSocket.SMTPConnection._onSocketClose (/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/smtp-connection/index.js:195:42)
    at Object.onceWrapper (node:events:628:26)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.emit (node:domain:489:12)
    at node:net:322:12
    at Socket.done (node:_tls_wrap:588:7)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12) {
  code: 'ECONNECTION',
  command: 'CONN'
}

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.
`

我试用的是腾讯的邮箱，不论是否开启tls都不行

**Comment by Kerwin1202** [comment]
没有配置 看不出 只能自己搜下了，腾讯的邮箱分qq 和 腾讯企业邮箱，配置host port都不一样 而且密码都不是密码 而是专用密码

**Comment by JinLiGame** [comment]
腾讯邮箱只能用ssl

**Comment by lszhwxa** [comment]
qq邮箱配置方法：登录后点设置-账户-POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务，打开，然后生成授权码，按照提示发送短信

**Comment by jjustwin** [comment]
换了端口后正常
