### ISSUE TITLE
部署本地报错，大佬们看看

### ISSUE THREAD

**Issue by hieivip** [Kerwin1202/chatgpt-web#80]
后端报数据库配置错误
c:\Users\Administrator\Desktop\chatGPT\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\cmap\connection.js:201
                    callback(new error_1.MongoServerError(document));
                             ^

MongoServerError: Authentication failed.
    at Connection.onMessage (c:\Users\Administrator\Desktop\chatGPT\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\cmap\connection.js:201:30)
    at MessageStream.<anonymous> (c:\Users\Administrator\Desktop\chatGPT\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\cmap\connection.js:59:60)
    at MessageStream.emit (node:events:513:28)
    at MessageStream.emit (node:domain:489:12)
    at processIncomingData (c:\Users\Administrator\Desktop\chatGPT\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\cmap\message_stream.js:124:16)
    at MessageStream._write (c:\Users\Administrator\Desktop\chatGPT\chatgpt-web-main\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22) {
  ok: 0,
  code: 18,
  codeName: 'AuthenticationFailed',
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.
 我通过工具是可以链接成功的 为啥启动不起来呢？
 
![image](https://user-images.githubusercontent.com/54146330/234764363-1a3cebcd-89d3-4f10-9bf3-e2b0b61c6934.png)

**Comment by huangwb8** [comment]
@hieivip 

如果你使用的是API模式，这提示你没有额度了。 你需要绑定openai的payment methods才可以正常使用。

**Comment by hieivip** [comment]
> @hieivip
> 
> 如果你使用的是API模式，这提示你没有额度了。 你需要绑定openai的payment methods才可以正常使用。

ok了，是我的key 弄错了。

还有一个问题就是 为啥我访问不出注册登录页面，直接进到了 对话框

**Comment by hieivip** [comment]
![image](https://user-images.githubusercontent.com/54146330/234767161-dba81914-fc4c-460c-b54f-0a885591784f.png)
已经k可以回复了，就是没有提示登录和注册

**Comment by hieivip** [comment]
![image](https://user-images.githubusercontent.com/54146330/234767780-a1b18d8d-81f7-4dc8-ab0c-9e92faf57e00.png)
我这个源码好像不对呢，设置按钮都没有

**Comment by EvanDbg** [comment]
https://github.com/Kerwin1202/chatgpt-web/blob/fcf476d6071f7f2cccce8ee8f8725bd3122afceb/service/.env.example#L54
AUTH_SECRET_KEY=
